name: notificar_supervisores
services:
  send_menssages:
    build: .
    restart: unless-stopped
    volumes:
      - ./arquivos-gerados:/app/arquivos-gerados
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - RUN_MODE=scheduler